export const quizData = [
  {
    element: "al~ol",
    gloss: "nurture, grow",
    example: [
      "alimentary",
      "alma mater",
      "alumnus",
      "abolish",
      "adolescent",
      "adult",
    ],
  },
  {
    element: "am~im",
    gloss: "love",
    example: ["amorous", "amative", "amicable", "inimical"],
  },
  {
    element: "ann~enn",
    gloss: "year",
    example: ["annals", "per annum", "perennial", "millennium"],
  },
  {
    element: "apt~ept",
    gloss: "fit",
    example: ["adapt", "aptitude", "coapt", "adept", "inept"],
  },
  {
    element: "bol~bl",
    gloss: "throw",
    example: [
      "diabolical",
      "hyperbole",
      "metabolism",
      "symbol",
      "parabola",
      "parable",
      "emblem",
      "problem",
    ],
  },
  {
    element: "cap~cep~cip~cup",
    gloss: "take",
    example: [
      "capacious",
      "captive",
      "except",
      "incipient",
      "principle",
      "occupy",
      "recuperate",
    ],
  },
  {
    element: "cid~cis",
    gloss: "cut, kill",
    example: ["homicide", "incision", "excise", "concise", "caesura"],
  },
  {
    element: "cri",
    gloss: "judge, separate",
    example: ["critic", "criterion", "crisis", "hypocrisy", "endocrine"],
  },
  {
    element: "cri~cre~cer",
    gloss: "separate",
    example: ["certain", "discern", "secern", "secret", "discrete", "secrete"],
  },
  {
    element: "cub~cumb",
    gloss: "lie down",
    example: ["cubicle", "concubine", "incubate", "incumbent", "recumbent"],
  },
  {
    element: "de~div",
    gloss: "god",
    example: ["deity", "deification", "divine", "divinity", "diva"],
  },
  {
    element: "equ~iqu",
    gloss: "even",
    example: [
      "equal",
      "equate",
      "equity",
      "equidistant",
      "equanimity",
      "adequate",
      "iniquity",
    ],
  },
  {
    element: "erg~org~urg",
    gloss: "work",
    example: [
      "energy",
      "ergative",
      "organ",
      "orgy",
      "georgic",
      "demiurge",
      "liturgy",
      "metallurgy",
    ],
  },
  {
    element: "fac~fec~fic",
    gloss: "do, make",
    example: [
      "fact",
      "factor",
      "factory",
      "facsimile",
      "factotum",
      "defect",
      "perfect",
      "prefect",
      "artificial",
      "deficit",
      "suffice",
    ],
  },
  {
    element: "frag~frang~fring",
    gloss: "break",
    example: [
      "fragile",
      "fragment",
      "fracture",
      "frangible",
      "refringent",
      "infringe",
    ],
  },
  {
    element: "fund~fus",
    gloss: "pour, melt",
    example: [
      "refund",
      "fuse",
      "fusion",
      "fusile",
      "diffuse",
      "effusive",
      "infuse",
    ],
  },
  {
    element: "gen~gn~na",
    gloss: "birth",
    example: [
      "general",
      "genus",
      "genius",
      "genial",
      "genital",
      "gentile",
      "genuine",
      "indigenous",
      "progeny",
      "benign",
      "pregnant",
      "innate",
      "native",
      "nation",
      "natal",
      "agnate",
    ],
  },
  {
    element: "gen~gon",
    gloss: "birth",
    example: ["gene", "genesis", "genocide", "heterogeneous", "gonad"],
  },
  {
    element: "i~it",
    gloss: "go",
    example: ["ion", "initial", "exit", "transit"],
  },
  {
    element: "men~mon",
    gloss: "think",
    example: [
      "mental",
      "dementia",
      "memento",
      "mention",
      "admonish",
      "monster",
    ],
  },
  {
    element: "mne",
    gloss: "remember",
    example: ["amnesia", "mnemonic"],
  },
  {
    element: "mov~mo",
    gloss: "move",
    example: [
      "motor",
      "motion",
      "emotion",
      "motility",
      "motive",
      "promote",
      "mobile",
    ],
  },
  {
    element: "nec~necr",
    gloss: "die",
    example: ["nectar", "nectarine", "necrology", "necrosis"],
  },
  {
    element: "nec~noc~nic~nox",
    gloss: "harm",
    example: ["internecine", "pernicious", "innocent", "innocuous", "noxious"],
  },
  {
    element: "pend~pond",
    gloss: "hang, weigh",
    example: [
      "depend",
      "appendix",
      "expend",
      "pendulum",
      "vilipend",
      "ponder",
      "preponderate",
    ],
  },
  {
    element: "sacr~sanc~secr",
    gloss: "holy",
    example: ["sacred", "sacrifice", "sanctify", "consecrate", "desecrate"],
  },
  {
    element: "semen~semin",
    gloss: "seed",
    example: ["semen", "inseminate", "seminal", "disseminate", "seminary"],
  },
  {
    element: "spec~spic",
    gloss: "look",
    example: [
      "spectacle",
      "spectrum",
      "specious",
      "speculate",
      "inspect",
      "retrospect",
      "despicable",
    ],
  },
  {
    element: "sta~ste",
    gloss: "stand",
    example: ["static", "thermostat", "ecstasy", "stasis", "system"],
  },
  {
    element: "sta~ste~sti~st",
    gloss: "stand",
    example: [
      "status",
      "stationary",
      "statute",
      "stable",
      "stamen",
      "obstetrician",
      "constitution",
      "institute",
      "prostitute",
      "insist",
      "interstice",
    ],
  },
  {
    element: "tag~teg~tig-tang~ting",
    gloss: "touch",
    example: [
      "contagion",
      "contact",
      "tax",
      "integer",
      "tangent",
      "tangible",
      "contingent",
    ],
  },
  {
    element: "tempor",
    gloss: "time",
    example: ["temporary", "temporize", "contemporary", "extemporaneous"],
  },
  {
    element: "ten~tin",
    gloss: "hold",
    example: [
      "tenable",
      "tenure",
      "tenacious",
      "retention",
      "continuous",
      "retinue",
    ],
  },
  {
    element: "tom~tm",
    gloss: "cut",
    example: [
      "anatomy",
      "atom",
      "microtome",
      "entomology",
      "epitome",
      "tmesis",
    ],
  },
  {
    element: "vic~vinc",
    gloss: "conquer",
    example: [
      "victor",
      "evict",
      "conviction",
      "convince",
      "evince",
      "invincible",
    ],
  },
  {
    element: "vor",
    gloss: "eat",
    example: ["carnivore", "omnivore", "voracious"],
  },
  {
    element: "zo",
    gloss: "animal",
    example: ["zoology", "protozoon", "zoomorphic", "azotometer"],
  },
  {
    element: "ana-",
    gloss: "up, again, back",
    example: [
      "analyze",
      "anabolic",
      "anachronism",
      "anaclastic",
      "analeptic",
      "analog",
    ],
  },
  {
    element: "ante-",
    gloss: "before",
    example: ["antebellum", "antecedent", "antedate", "anterior"],
  },
  {
    element: "аро-",
    gloss: "away from, off",
    example: [
      "apology",
      "apogee",
      "apoplectic",
      "apostasy",
      "apastron",
      "aphelion",
    ],
  },
  {
    element: "cata-",
    gloss: "down, backward",
    example: [
      "cataclysm",
      "catacomb",
      "catalepsy",
      "catalog",
      "catapult",
      "catalyst",
    ],
  },
  {
    element: "con-",
    gloss: "with",
    example: ["convene", "concomitant", "concord"],
  },
  {
    element: "contra-",
    gloss: "against, facing",
    example: ["contraceptive", "contradict", "contrapositive"],
  },
  {
    element: "de-",
    gloss: "reverse, from",
    example: ["decode", "demand", "denote", "deport", "descend", "destruction"],
  },
  {
    element: "dia-",
    gloss: "through",
    example: [
      "diameter",
      "dialog",
      "dialysis",
      "diathesis",
      "diocese",
      "diorama",
    ],
  },
  {
    element: "ec-",
    gloss: "out",
    example: [
      "appendectomy",
      "ecstatic",
      "tonsillectomy",
      "exegesis",
      "exodus",
    ],
  },
  {
    element: "ecto-",
    gloss: "outside",
    example: ["ectoplasm", "ectoderm", "ectomorph", "ectoparasite"],
  },
  {
    element: "en-",
    gloss: "in",
    example: ["energy", "encephalitis"],
  },
  {
    element: "endo-",
    gloss: "inside",
    example: ["endogamy", "endomorph", "endoscopy", "endarteritis"],
  },
  {
    element: "epi-",
    gloss: "on, over",
    example: ["epitaph", "epigram", "epitome", "epencephalic", "ephemeral"],
  },
  {
    element: "eu-",
    gloss: "good",
    example: [
      "eulogy",
      "euphemism",
      "euphony",
      "euphoria",
      "euthanasia",
      "eugenic",
    ],
  },
  {
    element: "ex-",
    gloss: "out",
    example: [
      "exact",
      "excavate",
      "except",
      "exfoliate",
      "extend",
      "educe",
      "egregious",
    ],
  },
  {
    element: "extra-",
    gloss: "outside",
    example: [
      "extraordinary",
      "extramarital",
      "extraneous",
      "extraterrestrial",
    ],
  },
  {
    element: "hetero-",
    gloss: "other",
    example: [
      "heterogeneous",
      "heterodont",
      "heterodox",
      "heteronomy",
      "heterosexual",
    ],
  },
  {
    element: "homo-",
    gloss: "same",
    example: ["homogenize", "homologous", "homosexual", "homatomic"],
  },
  {
    element: "hypo-",
    gloss: "under, below",
    example: [
      "hypodermic",
      "hypothermia",
      "hypothesis",
      "hypogeal",
      "hypalgia",
    ],
  },
  {
    element: "in-",
    gloss: "in, into",
    example: ["incite", "inception", "incinerate", "invade", "inoculate"],
  },

  {
    element: "in-",
    gloss: "not",
    example: [
      "inert",
      "inauthentic",
      "incompatible",
      "inequity",
      "illegal",
      "impossible",
      "irreverent",
      "ignorant",
    ],
  },
  {
    element: "infra-",
    gloss: "below",
    example: ["infrared", "infrastructure", "infralapsarian"],
  },
  {
    element: "inter-",
    gloss: "between",
    example: ["interfere", "intercalate", "interior", "interject", "internal"],
  },
  {
    element: "intra-",
    gloss: "within",
    example: ["intramural", "intrauterine", "intravenous"],
  },
  {
    element: "iso-",
    gloss: "equal",
    example: ["isometrics", "isosceles", "isopathy", "isobar", "isandrous"],
  },
  {
    element: "meso-",
    gloss: "middle",
    example: [
      "Mesolithic",
      "mesobiotic",
      "mesomorph",
      "Mesopotamian",
      "mesosphere",
    ],
  },
  {
    element: "meta-",
    gloss: "beyond",
    example: [
      "metadata",
      "metamorphosis",
      "metaphor",
      "metaphysics",
      "method",
      "metonymy",
    ],
  },
  {
    element: "ob-",
    gloss: "toward, against",
    example: ["object", "obdurate", "obit", "obloquy", "obstacle", "omit"],
  },
  {
    element: "para-",
    gloss: "beside, nearly",
    example: [
      "parallel",
      "paramedic",
      "paranormal",
      "paragraph",
      "parenthesis",
      "parody",
    ],
  },
  {
    element: "per-",
    gloss: "through, thorough",
    example: ["perturb", "pernicious", "perspicacity", "pervade"],
  },
  {
    element: "peri-",
    gloss: "around, near",
    example: ["perimeter", "perihelion", "periscope"],
  },
  {
    element: "post-",
    gloss: "after, behind",
    example: [
      "posterior",
      "posterity",
      "postpartum",
      "postpose",
      "postprandial",
      "postwar",
    ],
  },
  {
    element: "pre-",
    gloss: "before",
    example: ["prehistoric", "preadolescent", "prewashed"],
  },
  {
    element: "pro-",
    gloss: "forward, for",
    example: ["proceed", "prowar", "provide", "procure", "produce"],
  },
  {
    element: "re-",
    gloss: "again, back",
    example: ["reappoint", "redo", "review", "redundant"],
  },
  {
    element: "se-",
    gloss: "apart",
    example: ["separate", "select", "seduce", "segregate", "sedition"],
  },
  {
    element: "sub-",
    gloss: "under",
    example: [
      "subhuman",
      "subclass",
      "subreption",
      "success",
      "suffuse",
      "suborn",
    ],
  },
  {
    element: "super-",
    gloss: "above",
    example: [
      "superpower",
      "supercilious",
      "superficial",
      "supersede",
      "supreme",
    ],
  },
  {
    element: "syn-",
    gloss: "with",
    example: [
      "synergy",
      "synchronize",
      "syllogism",
      "sympathy",
      "symphony",
      "systolic",
      "system",
    ],
  },
  {
    element: "trans-",
    gloss: "across, through",
    example: [
      "transaction",
      "trans-Atlantic",
      "transfigure",
      "translucent",
      "transparent",
      "traverse",
    ],
  },
];

export const elementsArray = [
  "al~ol",
  "am~im",
  "ann~enn",
  "apt~ept",
  "bol~bI",
  "cap~cep~cip~cup",
  "cid~cis",
  "cri",
  "cri~cre~cer",
  "cub~cumb",
  "de~div",
  "equ~iqu",
  "erg~org~urg",
  "fac~fec~fic",
  "frag~frang~fring",
  "fund~fus",
  "gen~gn~na",
  "gen~gon",
  "i~it",
  "men~mon",
  "mne",
  "mov~mo",
  "nec~necr",
  "nec~noc~nic~nox",
  "pend~pond",
  "sacr~sanc~secr",
  "semen~semin",
  "spec~spic",
  "sta~ste",
  "sta~ste~sti~st",
  "tag~teg~tig-tang~ting",
  "tempor",
  "ten~tin",
  "tom~tm",
  "vic~vinc",
  "vor",
  "zo",
  "ana-",
  "ante-",
  "аро-",
  "cata-",
  "con-",
  "contra-",
  "de-",
  "dia-",
  "ec-",
  "ecto-",
  "en-",
  "endo-",
  "epi-",
  "eu-",
  "ex-",
  "extra-",
  "hetero-",
  "homo-",
  "hypo-",
  "in-",
  "in-",
  "infra-",
  "inter-",
  "intra-",
  "iso-",
  "meso-",
  "meta-",
  "ob-",
  "para-",
  "per-",
  "peri-",
  "post-",
  "pre-",
  "pro-",
  "re-",
  "se-",
  "sub-",
  "super-",
  "syn-",
  "trans-",
];

export const glossesArray = [
  "nurture, grow",
  "love",
  "year",
  "fit",
  "throw",
  "take",
  "cut, kill",
  "judge, separate",
  "separate",
  "lie down",
  "god",
  "even",
  "work",
  "do, make",
  "break",
  "pour, melt",
  "birth",
  "birth",
  "go",
  "think",
  "remember",
  "move",
  "die",
  "harm",
  "hang, weigh",
  "holy",
  "seed",
  "look",
  "stand",
  "stand",
  "touch",
  "time",
  "hold",
  "cut",
  "conquer",
  "eat",
  "animal",
  "up, again, back",
  "before",
  "away from, off",
  "down, backward",
  "with",
  "against, facing",
  "reverse, from",
  "through",
  "out",
  "outside",
  "in",
  "inside",
  "on, over",
  "good",
  "out",
  "outside",
  "other",
  "same",
  "under, below",
  "in, into",
  "not",
  "below",
  "between",
  "within",
  "equal",
  "middle",
  "beyond",
  "toward, against",
  "beside, nearly",
  "through, thorough",
  "around, near",
  "after, behind",
  "before",
  "forward, for",
  "again, back",
  "apart",
  "under",
  "above",
  "with",
  "across, through",
];
