export const quizData = [
  {
    element: "anim",
    gloss: "soul",
    example: ["animate", "animosity", "animadversion", "unanimous"],
  },
  {
    element: "corp",
    gloss: "body",
    example: [
      "corps",
      "corpse",
      "corpus",
      "corpuscle",
      "corpulent",
      "incorporate",
    ],
  },
  {
    element: "culp",
    gloss: "fault",
    example: ["culpable", "culprit", "exculpate", "mea culpa"],
  },
  {
    element: "duc",
    gloss: "to lead",
    example: [
      "educate",
      "induce",
      "introduce",
      "duct",
      "conduct",
      "product",
      "ductile",
      "dukes",
    ],
  },
  {
    element: "fug",
    gloss: "flee",
    example: ["fugitive", "fugue", "centrifuge", "refuge", "fugacious"],
  },
  {
    element: "grat",
    gloss: "goodwill",
    example: [
      "grateful",
      "gratis",
      "gratuity",
      "congratulate",
      "ingrate",
      "ingratiate",
      "grace",
      "gracious",
    ],
  },
  {
    element: "greg",
    gloss: "social group",
    example: ["gregarious", "congregation", "egregious", "segregate"],
  },
  {
    element: "hom",
    gloss: "human",
    example: ["homicide", "hominid", "Homo sapiens"],
  },
  {
    element: "anthrop",
    gloss: "Human",
    example: ["anthropology", "anthropomorphic", "philanthropy"],
  },
  {
    element: "bi",
    gloss: "life",
    example: [
      "biography",
      "biology",
      "bioluminescent",
      "macrobiotic",
      "microbial",
    ],
  },
  {
    element: "cac",
    gloss: "bad",
    example: ["cacophony", "caconym", "cacodemonic"],
  },
  {
    element: "chrom",
    gloss: "color",
    example: ["chrome", "monochrome", "chromosome", "chromatic"],
  },
  {
    element: "chron",
    gloss: "time",
    example: ["chronic", "diachronic", "chronometer", "anachronistic"],
  },
  {
    element: "cosm",
    gloss: "universe, adorn, order",
    example: [
      "cosmic",
      "cosmetic",
      "macrocosm",
      "cosmopolitan",
      "cosmogony",
      "cosmonaut",
      "cosmecology",
    ],
  },

  {
    element: "gam",
    gloss: "marry, unite",
    example: [
      "monogamy",
      "bigamy",
      "exogamous",
      "gamete",
      "epigamic",
      "gamogenesis",
    ],
  },
  {
    element: "iatr",
    gloss: "heal",
    example: ["pediatrician", "iatrogenic", "psychiatry", "geriatric"],
  },
  {
    element: "idi",
    gloss: "personal",
    example: [
      "idiosyncrasy",
      "idiom",
      "idiot",
      "idiolect",
      "idiomorphic",
      "idiopathy",
      "idiochromatic",
    ],
  },
  {
    element: "log",
    gloss: "speak, study",
    example: [
      "logic",
      "logo",
      "anthropology",
      "analogy",
      "eulogy",
      "prologue",
      "logorrhea",
    ],
  },
  {
    element: "macr",
    gloss: "large",
    example: [
      "macro",
      "macron",
      "macroeconomics",
      "macrocephalic",
      "macrocyte",
      "macradenous",
    ],
  },
  {
    element: "micr",
    gloss: "small",
    example: [
      "microbe",
      "microcosm",
      "micron",
      "microphotography",
      "microscope",
      "micranatomy",
    ],
  },
  {
    element: "mis",
    gloss: "hate",
    example: ["misanthrope", "misogamy", "misogyny", "misology"],
  },
  {
    element: "morph",
    gloss: "form",
    example: [
      "morpheme",
      "morphology",
      "amorphous",
      "polymorphous",
      "ectomorph",
      "endomorph",
      "astronomy",
      "autonomy",
      "metronome",
      "nomad",
      "nomology",
    ],
  },
  {
    element: "nom",
    gloss: "law, system",
    example: ["pathetic", "pathology", "pathos", "empathy", "sympathy"],
  },
  {
    element: "path",
    gloss: "feel, illness",
    example: ["anthropology", "anthropomorphic", "philanthropy"],
  },
  {
    element: "petr",
    gloss: "rock",
    example: ["petrify", "petroglyph", "petroleum", "petrous"],
  },
  {
    element: "phil",
    gloss: "liking",
    example: [
      "philosophy",
      "philanthropy",
      "Anglophile",
      "hemophilia",
      "philately",
    ],
  },
  {
    element: "phon",
    gloss: "sound",
    example: [
      "phonics",
      "phonetic",
      "telephone",
      "cacophony",
      "euphony",
      "symphonic",
      "aphonia",
    ],
  },
  {
    element: "pol",
    gloss: "community",
    example: ["politics", "police", "cosmopolitan", "metropolis"],
  },
  {
    element: "pseud",
    gloss: "false",
    example: [
      "pseudonym",
      "pseudopod",
      "pseudoscience",
      "pseudo-argument",
      "pseudandry",
    ],
  },
  {
    element: "psych",
    gloss: "mind",
    example: ["psyche", "psychic", "psychiatry", "psychopath", "psychotic"],
  },
  {
    element: "pyr",
    gloss: "fire",
    example: [
      "pyromaniac",
      "pyrometer",
      "pyrotechnics",
      "pyrite",
      "antipyretic",
    ],
  },
  {
    element: "the",
    gloss: "god",
    example: ["theology", "theocracy", "theogony", "polytheism", "atheist"],
  },
  {
    element: "top",
    gloss: "place",
    example: ["topic", "topical", "topology", "toponym", "isotope"],
  },
  {
    element: "xen",
    gloss: "foreign",
    example: [
      "xenophobia",
      "xenon",
      "xenogamy",
      "xenoplastic",
      "axenic",
      "pyroxene",
    ],
  },
  {
    element: "leg",
    gloss: "law, deputize",
    example: [
      "legal",
      "legacy",
      "allege",
      "relegate",
      "privilege",
      "legislature",
    ],
  },
  {
    element: "libr",
    gloss: "balance, weigh",
    example: ["equilibrium", "Libra", "libration"],
  },
  {
    element: "liter",
    gloss: "letter",
    example: [
      "literal",
      "literary",
      "Titerati",
      "alliteration",
      "obliterate",
      "transliterate",
    ],
  },
  {
    element: "nov",
    gloss: "new",
    example: ["novelty", "nova", "novice", "novitiate", "innovate", "renovate"],
  },
  {
    element: "omn",
    gloss: "all",
    example: ["omnipotent", "omniscient", "omnivorous", "omneity"],
  },
  {
    element: "par",
    gloss: "give birth to, produce",
    example: [
      "parent",
      "prepare",
      "separate",
      "parturition",
      "apparatus",
      "oviparous",
      "postpartum",
    ],
  },
  {
    element: "pet",
    gloss: "seek, go to",
    example: [
      "petition",
      "appetite",
      "centripetal",
      "impetus",
      "perpetual",
      "compete",
      "repeat",
      "petulant",
    ],
  },
  {
    element: "pot",
    gloss: "able, powerful",
    example: ["potent", "potential", "impotent", "omnipotent", "possible"],
  },
  {
    element: "prob",
    gloss: "good, test",
    example: ["probe", "probable", "probity", "approbation", "reprobate"],
  },
  {
    element: "sci",
    gloss: "know",
    example: [
      "science",
      "conscious",
      "omniscience",
      "prescient",
      "plebiscite",
      "adscititious",
      "sciolism",
    ],
  },
  {
    element: "sec",
    gloss: "cut",
    example: ["sect", "sector", "secant", "bisect", "insect", "transect"],
  },
  {
    element: "somn",
    gloss: "sleep",
    example: ["insomnia", "somnambulism", "somnolent", "soporific"],
  },
  {
    element: "ven",
    gloss: "come",
    example: ["venuz-rovenance", "intervene", "contravene", "eventual"],
  },
  {
    element: "ver",
    gloss: "true",
    example: [
      "verify",
      "aver",
      "verdict",
      "veritable",
      "veracity",
      "verisimilitude",
    ],
  },
];

export const elementsArray = [
  "anim",
  "corp",
  "culp",
  "duc",
  "fug",
  "grat",
  "greg",
  "hom",
  "anthrop",
  "bi",
  "cac",
  "chrom",
  "chron",
  "cosm",
  "gam",
  "iatr",
  "idi",
  "log",
  "macr",
  "micr",
  "mis",
  "morph",
  "nom",
  "path",
  "petr",
  "phil",
  "phon",
  "pol",
  "pseud",
  "psych",
  "pyr",
  "the",
  "top",
  "xen",
  "leg",
  "libr",
  "liter",
  "nov",
  "omn",
  "par",
  "pet",
  "pot",
  "prob",
  "sci",
  "sec",
  "somn",
  "ven",
  "ver",
];

export const glossesArray = [
  "soul",
  "body",
  "fault",
  "to lead",
  "flee",
  "goodwill",
  "social group",
  "human",
  "Human",
  "life",
  "bad",
  "color",
  "time",
  "universe, adorn, order",
  "marry, unite",
  "heal",
  "personal",
  "speak, study",
  "large",
  "small",
  "hate",
  "form",
  "law, system",
  "feel, illness",
  "rock",
  "liking",
  "sound",
  "community",
  "false",
  "mind",
  "fire",
  "god",
  "place",
  "foreign",
  "law, deputize",
  "balance, weigh",
  "letter",
  "new",
  "all",
  "give birth to, produce",
  "seek, go to",
  "able, powerful",
  "good, test",
  "know",
  "cut",
  "sleep",
  "come",
  "true",
];
